---
name: cmpsc-203-spring-2020-lab8
break: true
indent: 4
---

# --> check the technical writing
conduct.md:
    ConfirmFileExists

# --> check the technical writing
reflection.md:
    ConfirmFileExists
    CountFileWords --count 500
    CountMarkdownTags --tag "heading" --count 14 --exact
    CountMarkdownTags --tag "code_block" --count 2 --exact
    CountMarkdownTags --tag "list" --count 6 --exact
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact

# --> check the assessment writing
assessment.md:
    ConfirmFileExists
    CountFileParagraphs --count 50
    CountMarkdownTags --tag "heading" --count 12 --exact
    MatchFileFragment --fragment "Add Your Name Here" --count 0 --exact
    MatchFileFragment --fragment "TODO" --count 0 --exact

# --> check the number of commits beyond a threshold
CountCommits --count 5
